messages.only-players=Only players can use this command.
messages.wrong-material=Please enter a valid material.
messages.wrong-tool=Please enter a valid tool.
messages.enter-type=Please enter a tool type (pickaxe, axe, shovel).
messages.enter-tier=Please enter a tool tier.
messages.invfull={material} {tool} could not be added to your inventory because it is full.
messages.reloadplugin=Plugin reload is successful.
messages.reloadplugin-actionbar=Reloaded Plugin
messages.use-give=Use: /amethysttoolsgive <player> <tier> <type>
messages.player-notfound={player} not found.
messages.player-notfound-actionbar=Player not found
item.name=Amethyst
item.pickaxe=Pickaxe
item.axe=Axe
item.shovel=Shovel
menus.root=Amethyst Tools
menus.wooden=Wooden Tools
menus.stone=Stone Tools
menus.iron=Iron Tools
menus.copper=Copper Tools
menus.golden=Golden Tools
menus.diamond=Diamond Tools
menus.netherite=Netherite Tools
menus.back=Previous Page
