messages.only-players=Only players can use this command.
messages.wrong-material=Please enter a valid material.
messages.wrong-tool=Please enter a valid tool.
messages.empty-arg2=Please enter a tool type (pickaxe, axe, shovel).
messages.invfull={material} {tool} could not be added to your inventory because it is full.
messages.invfull-actionbar=Your inventory is full!
messages.reloadplugin=Plugin reload is succesfuly complete.
messages.reloadplugin-actionbar=Reloaded Plugin
messages.nopermission=You don't have permission!
messages.nopermission-actionbar=You don't have permission!
messages.use-give=Use: /amethysttoolsgive <player> <tier> <type>
messages.player-notfound={player} not found.
messages.player-notfound-actionbar=Player not found
messages.enter-tier=Please enter a tool tier.
messages.toolgiven=Tool given.
item.item-name=Amethyst
item.item-pickaxe=Pickaxe
item.item-axe=Axe
item.item-shovel=Shovel
menus.menu-main=Amethyst Tools
menus.menu-wooden=Wooden Tools
menus.menu-stone=Stone Tools
menus.menu-iron=Iron Tools
menus.menu-copper=Copper Tools
menus.menu-golden=Golden Tools
menus.menu-diamond=Diamond Tools
menus.menu-netherite=Netherite Tools
menus.item-previous=Previous Page
