plugins {
    id 'net.fabricmc.fabric-loom-remap' version '1.16.1'
    id 'maven-publish'
}

group = 'com.rtc'
version = '1.4'

base {
    archivesName = 'AmethystTools'
}

repositories {
    mavenCentral()
    maven {
        url = 'https://maven.fabricmc.net/'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.11"
    mappings "net.fabricmc:yarn:1.21.11+build.6:v2"
    modImplementation "net.fabricmc:fabric-loader:0.18.1"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.141.0+1.21.11"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}

sourceSets {
    main {
        java.srcDirs = ['src/fabric/java']
        resources.srcDirs = ['src/fabric/resources']
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

processResources {
    inputs.property 'version', version
    filteringCharset 'UTF-8'
    filesMatching('fabric.mod.json') {
        expand version: version
    }
}
